controller_manager:
  ros__parameters:
    update_rate: 1000

    # Robot arm controller
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Robot gripper controller
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Joint state broadcaster - Dafult controller
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    joints:
      - base_shoulder
      - shoulder_elbow
      - elbow_wrist
      - wrist_ulna
      - ulna_febur
      - febur_gripper

    command_interfaces:
      - position
        
    state_interfaces:
      - position

gripper_controller:
  ros__parameters:
    joints:
      - right_finger

    command_interfaces:
      - position
        
    state_interfaces:
      - position